### ISSUE TITLE
Wrapping breaks justification

### ISSUE THREAD

**Issue by timonegk** [ntjess/wrap-it#4]
Justification at the end of the wrapped content is wrong. This can also be seen on the example images in the README (e.g., example-1.png). A workaround is to manually insert a `#linebreak(justify: true)`.

**Comment by staeff777** [comment]
Thanks für the workaround. Where are you inserting the linebreak?

**Comment by timonegk** [comment]
I am adding it where the wrong justification is happening

**Comment by ntjess** [comment]
Closed in de8343d
