### ISSUE TITLE
Deprecation warnings in Typst 0.12

### ISSUE THREAD

**Issue by TheJanzap** [ntjess/wrap-it#5]
Typst 0.12 shows the following deprecation warnings for wrap-it:
- Calling `measure` with a styles argument is deprecated
- Calling `measure` with a styles argument is deprecated
- `style` is deprecated

**Comment by Servostar** [comment]
Opened PR #6

**Comment by ntjess** [comment]
Closed in de8343d

**Comment by TheJanzap** [comment]
@ntjess Thanks for the fix! But it seems that the new version is not showing up on Typst Universe. I reckon you'd need to create a new tag for this version?

**Comment by ntjess** [comment]
The commits were present on this repo, but I waited to submit the official package version until I fixed a few quirks with the readme images. It should be available in the next few days once https://github.com/typst/packages/pull/1340 is merged.
